@extends('layouts.admin')
@section('title', 'Check in')
@section('header', 'Front desk check-in')

@section('content')
<div class="mx-auto max-w-5xl"><x-admin.page-header eyebrow="Front desk" title="Customer check-in" description="Search by partial name or phone number. Today’s appointments are always prioritised." /><x-admin.form-errors /><form class="mt-8 flex gap-3 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5" method="GET" action="{{ route('admin.check-in.index') }}"><input class="form-input text-lg" name="q" value="{{ $search }}" placeholder="Name or phone number" autofocus><button class="brand-button shrink-0 px-6 py-3" style="--brand:#047857" type="submit">Search</button></form>
    <div class="mt-6 space-y-4">@forelse($appointments as $appointment)<article class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><div class="grid gap-5 sm:grid-cols-[1fr_auto] sm:items-center"><div><div class="flex flex-wrap items-center gap-3"><h2 class="text-xl font-black text-slate-950">{{ $appointment->customer_name }}</h2><x-admin.status-badge :status="$appointment->status" /></div><p class="mt-2 font-bold text-slate-600">{{ $appointment->customer_phone }}</p><div class="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm text-slate-500"><span class="font-black {{ $appointment->appointment_date->toDateString() === $today ? 'text-emerald-700' : '' }}">{{ $appointment->appointment_date->toDateString() === $today ? 'Today' : $appointment->appointment_date->format('D, j M') }} · {{ Carbon\CarbonImmutable::parse($appointment->start_time)->format('g:i A') }}</span><span>{{ $appointment->service->name }}</span></div></div><div class="flex flex-wrap gap-2"><a class="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-black text-slate-700 hover:bg-slate-50" href="{{ route('admin.appointments.show', $appointment) }}">View</a>@if($appointment->status->canCheckIn())<form action="{{ route('admin.check-in.store', $appointment) }}" method="POST">@csrf<button class="brand-button px-5 py-2.5" style="--brand:#d97706" type="submit">Check in</button></form>@endif</div></div></article>@empty<div class="rounded-3xl border border-slate-200 bg-white px-6 py-16 text-center shadow-sm"><p class="font-black text-slate-900">No matching appointments</p><p class="mt-2 text-sm text-slate-500">Check spelling or try a phone number without spaces or dashes.</p></div>@endforelse</div>
    @if(!$search)<p class="mt-5 text-center text-xs text-slate-400">Showing today’s appointments. Search to include other dates.</p>@endif
</div>
@endsection
