@extends('layouts.admin')
@section('title', $appointment->customer_name)
@section('header', 'Appointment details')

@section('content')
<div class="mx-auto max-w-6xl"><div class="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><a class="text-sm font-black text-slate-500 hover:text-slate-900" href="{{ route('admin.appointments.index') }}">← Appointments</a><div class="mt-4 flex flex-wrap items-center gap-3"><h1 class="text-3xl font-black tracking-[-.035em] text-slate-950">{{ $appointment->customer_name }}</h1><x-admin.status-badge :status="$appointment->status" />@if($staffingStatus['managed'] && ! $staffingStatus['healthy'])<span class="rounded-full bg-rose-50 px-3 py-1 text-xs font-black text-rose-700 ring-1 ring-rose-200">⚠ Staffing conflict</span>@endif</div><p class="mt-2 text-slate-500">Booked {{ $appointment->created_at->timezone($currentBusiness->timezone)->format('j M Y, g:i A') }}</p></div>
    <div class="flex flex-wrap gap-2">@if($appointment->status->canCheckIn())<form action="{{ route('admin.appointments.check-in', $appointment) }}" method="POST">@csrf<button class="brand-button px-5 py-3" style="--brand:#d97706" type="submit">Check in</button></form>@endif @if($appointment->status->canComplete())<form action="{{ route('admin.appointments.complete', $appointment) }}" method="POST" onsubmit="return confirm('Mark this appointment as completed?')">@csrf<button class="brand-button px-5 py-3" style="--brand:#047857" type="submit">Complete</button></form>@endif @if(in_array($appointment->status, [App\Enums\AppointmentStatus::Booked, App\Enums\AppointmentStatus::CheckedIn], true))<form action="{{ route('admin.appointments.cancel', $appointment) }}" method="POST" onsubmit="return confirm('Cancel this appointment?')">@csrf<button class="rounded-xl border border-rose-200 bg-white px-5 py-3 text-sm font-black text-rose-600 hover:bg-rose-50" type="submit">Cancel</button></form>@endif @if($appointment->status === App\Enums\AppointmentStatus::Booked)<form action="{{ route('admin.appointments.no-show', $appointment) }}" method="POST" onsubmit="return confirm('Mark this customer as a no show?')">@csrf<button class="rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-black text-slate-600 hover:bg-slate-50" type="submit">No show</button></form>@endif</div></div>
    <x-admin.form-errors />

    @if($staffingStatus['managed'] && ! $staffingStatus['healthy'])
        <div class="mt-7 rounded-3xl border border-rose-200 bg-rose-50 p-6"><p class="font-black text-rose-900">This appointment is understaffed.</p><p class="mt-1 text-sm leading-6 text-rose-700">It requires {{ $staffingStatus['required'] }} qualified {{ Str::plural('worker', $staffingStatus['required']) }}, but only {{ $staffingStatus['assigned'] }} {{ $staffingStatus['assigned'] === 1 ? 'worker is' : 'workers are' }} currently assigned and available. The customer booking remains confirmed.</p><a class="mt-4 inline-flex rounded-xl bg-white px-4 py-2 text-sm font-black text-rose-700 ring-1 ring-rose-200" href="{{ route('admin.workers.index', ['date' => $appointment->appointment_date->format('Y-m-d')]) }}">Manage workers →</a></div>
    @endif

    <div class="mt-8 grid gap-8 lg:grid-cols-[1.15fr_.85fr]"><div class="space-y-8"><section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><h2 class="text-lg font-black text-slate-950">Appointment</h2><dl class="mt-6 grid gap-6 sm:grid-cols-2"><div><dt class="text-xs font-black uppercase tracking-[.16em] text-slate-400">Service</dt><dd class="mt-2 font-black text-slate-900">{{ $appointment->service->name }}</dd><dd class="mt-1 text-sm text-slate-500">{{ $appointment->service->category->name }}</dd></div><div><dt class="text-xs font-black uppercase tracking-[.16em] text-slate-400">Price</dt><dd class="mt-2 font-black text-slate-900">{{ $appointment->service->price === null ? 'Not set' : 'RM'.number_format((float) $appointment->service->price, 2) }}</dd><dd class="mt-1 text-sm text-slate-500">{{ $appointment->service->duration_minutes }} minutes · {{ $appointment->service->workers_required }} {{ Str::plural('worker', $appointment->service->workers_required) }}</dd></div><div><dt class="text-xs font-black uppercase tracking-[.16em] text-slate-400">Date</dt><dd class="mt-2 font-black text-slate-900">{{ $appointment->appointment_date->format('l, j F Y') }}</dd></div><div><dt class="text-xs font-black uppercase tracking-[.16em] text-slate-400">Time</dt><dd class="mt-2 font-black text-slate-900">{{ Carbon\CarbonImmutable::parse($appointment->start_time)->format('g:i A') }} – {{ Carbon\CarbonImmutable::parse($appointment->end_time)->format('g:i A') }}</dd></div></dl></section>

        <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div class="flex items-start justify-between gap-4"><div><h2 class="text-lg font-black text-slate-950">Assigned workers</h2><p class="mt-1 text-sm text-slate-500">Bookwise assigns the least-loaded qualified workers automatically.</p></div>@if($staffingStatus['managed'])<span class="rounded-full px-3 py-1 text-xs font-black {{ $staffingStatus['healthy'] ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700' }}">{{ $staffingStatus['assigned'] }}/{{ $staffingStatus['required'] }}</span>@endif</div>
            @if(! $staffingStatus['managed'])
                <div class="mt-5 rounded-2xl border border-violet-200 bg-violet-50 p-4 text-sm text-violet-800">Worker capacity is not configured for this business yet. <a class="font-black underline" href="{{ route('admin.workers.create') }}">Add a worker</a> to enable automatic assignments.</div>
            @elseif($staffingStatus['workers']->isEmpty())
                <div class="mt-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">No valid worker is currently assigned.</div>
            @else
                <div class="mt-5 grid gap-3 sm:grid-cols-2">@foreach($staffingStatus['workers'] as $worker)<div class="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3"><p class="font-black text-slate-900">{{ $worker->name }}</p><p class="mt-1 text-xs text-slate-500">Qualified · available</p></div>@endforeach</div>
            @endif
        </section>

        <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><h2 class="text-lg font-black text-slate-950">Customer</h2><dl class="mt-6 grid gap-6 sm:grid-cols-2"><div><dt class="text-xs font-black uppercase tracking-[.16em] text-slate-400">Name</dt><dd class="mt-2 font-black text-slate-900">{{ $appointment->customer_name }}</dd></div><div><dt class="text-xs font-black uppercase tracking-[.16em] text-slate-400">Phone</dt><dd class="mt-2"><a class="font-black text-emerald-700" href="tel:{{ $appointment->customer_phone_normalized }}">{{ $appointment->customer_phone }}</a></dd></div><div class="sm:col-span-2"><dt class="text-xs font-black uppercase tracking-[.16em] text-slate-400">Email</dt><dd class="mt-2 text-slate-700">{{ $appointment->customer_email ?: 'Not provided' }}</dd></div><div class="sm:col-span-2"><dt class="text-xs font-black uppercase tracking-[.16em] text-slate-400">Customer notes</dt><dd class="mt-2 whitespace-pre-line text-sm leading-6 text-slate-700">{{ $appointment->customer_notes ?: 'No customer notes.' }}</dd></div></dl></section></div>
    <div class="space-y-8"><section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-lg font-black text-slate-950">Timeline</h2><div class="mt-6 space-y-5 border-l-2 border-slate-100 pl-5 text-sm"><div><p class="font-black text-slate-800">Appointment booked</p><p class="mt-1 text-slate-500">{{ $appointment->created_at->timezone($currentBusiness->timezone)->format('j M Y, g:i A') }}</p></div>@if($appointment->checked_in_at)<div><p class="font-black text-amber-700">Checked in</p><p class="mt-1 text-slate-500">{{ $appointment->checked_in_at->timezone($currentBusiness->timezone)->format('j M Y, g:i A') }}</p></div>@endif @if($appointment->completed_at)<div><p class="font-black text-emerald-700">Completed</p><p class="mt-1 text-slate-500">{{ $appointment->completed_at->timezone($currentBusiness->timezone)->format('j M Y, g:i A') }}</p></div>@endif @if($appointment->cancelled_at)<div><p class="font-black text-rose-700">Cancelled</p><p class="mt-1 text-slate-500">{{ $appointment->cancelled_at->timezone($currentBusiness->timezone)->format('j M Y, g:i A') }}</p></div>@endif</div></section><section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-lg font-black text-slate-950">Internal notes</h2><form class="mt-5" action="{{ route('admin.appointments.update', $appointment) }}" method="POST">@csrf @method('PUT')<textarea class="form-input min-h-36" name="internal_notes" maxlength="3000" placeholder="Private notes for your team">{{ old('internal_notes', $appointment->internal_notes) }}</textarea><button class="brand-button mt-4 w-full px-5 py-3" style="--brand:#047857" type="submit">Save internal notes</button></form></section></div></div></div>
@endsection
